### ISSUE TITLE
Document development environment setup

### ISSUE THREAD

**Issue by murtoM** [murtoM/invekotin#2]
Create a GitHub wiki page for development environment setup containing:

- [ ] Docker installation and usage
- [ ] Prettier installation and usage (move from the style guide page)
- [ ] Possible modifications to the local git preferences (Docker might not like DOS newlines)
- [x] Example contents for `.env`
- [ ] something else?

**Comment by mtijas** [comment]
Started at https://github.com/murtoM/invekotin/wiki/Local-development-environment-setup

**Comment by murtoM** [comment]
There is no longer need for such verbose development environment setup instructions, let's assume that the developer can install and run `docker-compose`.
